import type { School, SchoolLevel } from "@/lib/types";

export const SEOUL_CENTER = {
  lat: 37.5665,
  lng: 126.978,
};

export const schools: School[] = [
  {
    id: "seoul-science-high",
    name: "서울과학고등학교",
    level: "high",
    category: "과학고",
    district: "서울 종로구",
    address: "서울특별시 종로구 혜화로 63",
    lat: 37.5919,
    lng: 127.0028,
    gender: "coed",
    founded: 1989,
    phone: "02-740-6299",
    website: "https://sshs.sen.hs.kr",
    tags: ["과학", "연구", "심화수업", "프로젝트"],
    description:
      "탐구 중심 수업과 연구 활동을 강하게 운영하는 과학계열 고등학교입니다.",
    highlights: ["연구 활동 중심", "심화 과학·수학", "프로젝트 발표 문화"],
    metrics: {
      academics: 96,
      activities: 91,
      environment: 82,
      meal: 72,
      reviews: 84,
      stability: 88,
    },
    facts: {
      students: 380,
      classes: 24,
      teachers: 78,
      clubs: 42,
      libraryBooks: 28000,
      mealSatisfaction: 4.1,
      commuteNote: "혜화·한성대입구 생활권",
    },
  },
  {
    id: "hanseong-middle",
    name: "한성중학교",
    level: "middle",
    category: "일반중",
    district: "서울 성북구",
    address: "서울특별시 성북구 삼선교로 16길 118",
    lat: 37.5886,
    lng: 127.0115,
    gender: "coed",
    founded: 1946,
    phone: "02-742-1321",
    website: "https://hanseong.sen.ms.kr",
    tags: ["생활지도", "독서", "동아리", "통학"],
    description:
      "도심 접근성과 생활지도 프로그램이 균형 잡힌 일반 중학교입니다.",
    highlights: ["통학 접근성", "독서 프로그램", "안정적인 생활지도"],
    metrics: {
      academics: 77,
      activities: 79,
      environment: 81,
      meal: 76,
      reviews: 80,
      stability: 86,
    },
    facts: {
      students: 610,
      classes: 25,
      teachers: 55,
      clubs: 28,
      libraryBooks: 18500,
      mealSatisfaction: 3.9,
      commuteNote: "버스 노선 접근이 쉬움",
    },
  },
  {
    id: "kyunggi-high",
    name: "경기고등학교",
    level: "high",
    category: "일반고",
    district: "서울 강남구",
    address: "서울특별시 강남구 영동대로 643",
    lat: 37.5172,
    lng: 127.0567,
    gender: "boys",
    founded: 1900,
    phone: "02-3496-7300",
    website: "https://kyunggi.sen.hs.kr",
    tags: ["진학", "자율활동", "도서관", "전통"],
    description:
      "진학 지원과 자율활동 기반이 탄탄한 서울권 일반 고등학교입니다.",
    highlights: ["진학 자료 축적", "동문 네트워크", "도서관 활용도"],
    metrics: {
      academics: 88,
      activities: 83,
      environment: 86,
      meal: 70,
      reviews: 82,
      stability: 89,
    },
    facts: {
      students: 920,
      classes: 36,
      teachers: 82,
      clubs: 47,
      libraryBooks: 31000,
      mealSatisfaction: 3.6,
      commuteNote: "삼성·청담권 지하철 접근",
    },
  },
  {
    id: "eunkwang-girls-high",
    name: "은광여자고등학교",
    level: "high",
    category: "일반고",
    district: "서울 강남구",
    address: "서울특별시 강남구 남부순환로359길 36",
    lat: 37.4865,
    lng: 127.0438,
    gender: "girls",
    founded: 1946,
    phone: "02-3462-2005",
    website: "https://eunkwang.sen.hs.kr",
    tags: ["진로", "상담", "급식", "분위기"],
    description:
      "상담과 진로 프로그램, 안정적인 학교 분위기가 강점인 여자고등학교입니다.",
    highlights: ["진로 상담", "차분한 분위기", "생활 만족도"],
    metrics: {
      academics: 83,
      activities: 81,
      environment: 88,
      meal: 84,
      reviews: 87,
      stability: 85,
    },
    facts: {
      students: 770,
      classes: 31,
      teachers: 69,
      clubs: 39,
      libraryBooks: 24800,
      mealSatisfaction: 4.3,
      commuteNote: "양재·도곡 생활권",
    },
  },
  {
    id: "sangmoon-high",
    name: "상문고등학교",
    level: "high",
    category: "일반고",
    district: "서울 서초구",
    address: "서울특별시 서초구 명달로 45",
    lat: 37.4861,
    lng: 127.0058,
    gender: "boys",
    founded: 1972,
    phone: "02-586-3141",
    website: "https://sangmoon.sen.hs.kr",
    tags: ["진학", "자율", "동아리", "학업"],
    description:
      "학업 분위기와 자율활동을 함께 중시하는 서초권 일반 고등학교입니다.",
    highlights: ["학업 분위기", "자율동아리", "진학 관리"],
    metrics: {
      academics: 86,
      activities: 80,
      environment: 79,
      meal: 73,
      reviews: 78,
      stability: 84,
    },
    facts: {
      students: 850,
      classes: 34,
      teachers: 74,
      clubs: 36,
      libraryBooks: 22100,
      mealSatisfaction: 3.7,
      commuteNote: "교대·방배권 버스 접근",
    },
  },
  {
    id: "seoul-robot-high",
    name: "서울로봇고등학교",
    level: "high",
    category: "특성화고",
    district: "서울 강남구",
    address: "서울특별시 강남구 광평로20길 63",
    lat: 37.4835,
    lng: 127.096,
    gender: "coed",
    founded: 1994,
    phone: "02-2226-2141",
    website: "https://robot.sen.hs.kr",
    tags: ["로봇", "AI", "실습", "취업"],
    description:
      "로봇·자동화·AI 실습 기반의 진로 특화 교육과정을 운영하는 특성화고입니다.",
    highlights: ["전공 실습", "산학 연계", "프로젝트 포트폴리오"],
    metrics: {
      academics: 78,
      activities: 94,
      environment: 85,
      meal: 76,
      reviews: 82,
      stability: 80,
    },
    facts: {
      students: 540,
      classes: 23,
      teachers: 61,
      clubs: 34,
      libraryBooks: 15700,
      mealSatisfaction: 3.9,
      commuteNote: "수서·일원권 접근",
    },
  },
  {
    id: "daechi-middle",
    name: "대치중학교",
    level: "middle",
    category: "일반중",
    district: "서울 강남구",
    address: "서울특별시 강남구 남부순환로378길 39",
    lat: 37.4962,
    lng: 127.0622,
    gender: "coed",
    founded: 1986,
    phone: "02-552-1235",
    website: "https://daechi.sen.ms.kr",
    tags: ["학업", "통학", "동아리", "학습지원"],
    description:
      "학습 분위기와 생활권 접근성이 강점인 강남권 일반 중학교입니다.",
    highlights: ["학습 지원", "교통 접근", "활동 선택지"],
    metrics: {
      academics: 84,
      activities: 77,
      environment: 80,
      meal: 74,
      reviews: 79,
      stability: 83,
    },
    facts: {
      students: 690,
      classes: 27,
      teachers: 58,
      clubs: 30,
      libraryBooks: 19300,
      mealSatisfaction: 3.8,
      commuteNote: "대치·도곡 생활권",
    },
  },
  {
    id: "sinmok-middle",
    name: "신목중학교",
    level: "middle",
    category: "일반중",
    district: "서울 양천구",
    address: "서울특별시 양천구 목동중앙로 88",
    lat: 37.5267,
    lng: 126.8718,
    gender: "coed",
    founded: 1985,
    phone: "02-2643-0004",
    website: "https://sinmok.sen.ms.kr",
    tags: ["생활", "상담", "급식", "운동장"],
    description:
      "생활 만족도와 상담 프로그램, 넓은 활동 공간이 돋보이는 중학교입니다.",
    highlights: ["상담 프로그램", "급식 만족도", "활동 공간"],
    metrics: {
      academics: 76,
      activities: 82,
      environment: 86,
      meal: 88,
      reviews: 85,
      stability: 82,
    },
    facts: {
      students: 640,
      classes: 26,
      teachers: 57,
      clubs: 31,
      libraryBooks: 17600,
      mealSatisfaction: 4.4,
      commuteNote: "목동 생활권",
    },
  },
];

export function getSchoolById(id: string) {
  return schools.find((school) => school.id === id);
}

export function filterSchools(level: SchoolLevel | "all" = "all") {
  if (level === "all") {
    return schools;
  }

  return schools.filter((school) => school.level === level);
}
